language: C
cache: pip
install:
    - pip install --user sphinx==1.7.8
    - pip install --user sphinx_rtd_theme==0.4.3
    - pip install --user reportlab==3.5.19  
    - pip install --user rst2pdf==0.94
script: make htmlwerror
